# content of: tox.ini, put in same dir as setup.py
[tox]
skipsdist = true
envlist = py3{10}

[gh-actions]
python =
    3.10: py310

[testenv]
passenv = *
basepython =
    py310: python3.10
deps = 
    .[all]
    .[dev]
# Add pytest to the allowlist
allowlist_externals = pytest
commands = pytest -vv --maxfail=2 --cov=testbook --cov-report=xml -W always {posargs}