# AUTOGENERATED! DO NOT EDIT! File to edit: ../../modules_nbs/viz_scores.ipynb.

# %% auto 0
__all__ = ['get_curves', 'plot_binland', 'format_axin', 'get_binland_margin']

# %% ../../modules_nbs/viz_scores.ipynb 2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from roux.viz.ax_ import format_ax
def get_curves(
    # Define the target output values to plot
    targets = [
        1.0,
        0.75,
        0.5,
        0.25,
    ],
    ):
    """
    Generates and saves a plot visualizing the relationship lfc * compe = k
    for target values k = 0.1, 0.5, and 1.0, within the [0, 1] range.
    """
    dfs=[]
    for k in targets:
        lfc_vals = np.linspace(k, 2.1, 20)
        compe_vals = k / lfc_vals.clip(max=1)
        dfs.append(
            pd.DataFrame(
                dict(
                    lfc=lfc_vals,
                    compe=compe_vals,
                    robustness=k,
                    )
            )
        )
        
        compe_vals = np.linspace(1, 4, 2)
        dfs.append(
            pd.DataFrame(
                dict(
                    lfc=np.repeat(k,len(compe_vals)),
                    compe=compe_vals,
                    robustness=k,
                )
            )
        )
        
    return pd.concat(dfs)
def plot_binland(
    ax=None,
    logy=True,
    bins = [
        1.0,
        # 0.75,
        0.5,
        # 0.25,
    ],
    ):
    data=get_curves(
        targets=bins,
    )
    if logy:
        data=(
            data
                    .assign(
                        **{
                            'compe': lambda df: df['compe'].apply(np.log2),
                        }
                    ) 
        )
        
    if ax is None:
        ax=plt.gca()
        
    _=(
        data  
            .groupby('robustness')
                .apply(
                    lambda df: 
                        df.sort_values(['lfc','compe'],ascending=[False,True]).plot(
                            # x='LFC',
                            x='lfc',
                            y='compe',
                            label=df.name,
                            linestyle=':',
                            color='k',
                            clip_on=False,
                            ax=ax,   
                        )    
            )
    )
    ax.set(
        xlabel='Upregulation',
        ylabel='Compensation',
        xlim=[0,2],
        ylim=[-2,2],    
    )    
    format_ax(
        # kws_legend=dict(
        #     bbox_to_anchor=[1,1],
        # )
    )
    ax.legend_.remove()
    # ax.text(
    #     x=2.1,
    #     y=0.5,
    #     s=' Robustness\n score',
    # )
    ax.set_title(
        'Robustness',
        loc='left',
        # va='bottom',
        y=1.1,
    )
    _=( 
        data  
            .groupby('robustness',as_index=False)
                .apply(
                    lambda df: df.query(
                        # expr=f"`lfc` == {df['lfc'].max()}"
                        expr=f"`compe` == {df['compe'].max()}"
                    )
                )
        .apply(
            lambda x: ax.text(
                x['lfc'],
                x['compe']+0.1,
                # s=f" {x['robustness']}",
                s=f"{x['robustness']:.0g}",
                ha='center',
                # va='center',
                va='bottom',
                # bbox=dict(facecolor='white', alpha=0.75, edgecolor='none',pad=0),
            ),
            axis=1
        )
    )
    ax.bins=bins
    ax.logy=logy
    return ax

# %run ../../roux/roux/viz/figure.py
def format_axin(ax):
    ax.set(
        # yticks=[],
        # yticklabels=[],
        ylabel=None,
    )
    ax.tick_params(
        axis='y', 
        labelsize=10, # Example: Set font size to 16 points
        pad=1,
    )
    
    ax.xaxis.tick_top() 
    
    # # 4. Set the label's position explicitly to the top (ensures the label follows the axis)
    ax.xaxis.set_label_position('top')
    
    # # 5. Clear the bottom axis elements
    
    # a) Hide the bottom spine (the axis line itself)
    ax.spines['bottom'].set_visible(False)
    ax.spines['right'].set_visible(False)
    
    # b) Ensure bottom ticks and labels are hidden (often redundant after tick_top, but robust)
    ax.tick_params(
        axis='x', 
        bottom=False,      # Hide ticks on the bottom edge
        labelbottom=False  # Hide tick labels on the bottom edge
    )
    
    # c) Ensure the top ticks/labels are explicitly shown (for clarity/robustness)
    ax.tick_params(
        axis='x', 
        top=True,          # Show ticks on the top edge
        labeltop=True      # Show tick labels on the top edge
        # pad=1,
    )
    return ax
    
def get_binland_margin(
    ax,
    test=False,
    ax1x=1.25,
    ax2x='xmin',
    bounds=[1.2,0,0.4,0.5],
    kws_line={},
    xlim=None,
    **kws_ins
    ):
    axin=ax.inset_axes(
        bounds=bounds,
        **kws_ins
        )
    axin.set(
        xlim=xlim,
        ylim=[len(ax.bins)+0.5,-0.5],
        ylabel=None,
        # yticks=[],
        # yticklabels=[],
    )
    from roux.viz.figure import annot_axs
    assert ax.logy,ax.logy
    annot_axs(
        ax1=ax,
        ax2=axin,
        # data=pd.DataFrame({
        #     'ax1y': [0,-0.4,-1,-2],
        #     'ax2y': [0.5,1.5,2.5,3.5],
        # }),
        ## get ys from bins
        data=pd.DataFrame({
            'ax1y':[1.44 * np.log(x) for x in ax.bins],
            'ax2y':np.arange(0,len(ax.bins),1)+0.5,
        }),        
        cols=dict(
            # ax1x='xmax',
            ax1x=ax1x,
            ax1y='ax1y',
            ax2x=ax2x,
            ax2y='ax2y',
        ),
        **{
            **dict(
                color='k',
                linestyle=':',
                linewidth=1,
                # connectionstyle="arc,armA=30,angleA=0,rad=10",
                zorder=0,
            ),
            **kws_line,
        },
        # verbose=True
    )
    axin=format_axin(axin)
    return axin
