# AUTOGENERATED! DO NOT EDIT! File to edit: ../../modules_nbs/stats_diffs.ipynb.

# %% auto 0
__all__ = ['get_diff_ins', 'get_ro', 'get_diff', 'ttest', 'get_diff_shrunk']

# %% ../../modules_nbs/stats_diffs.ipynb 1
import logging
import numpy as np
import pandas as pd

# ## common functions
def _remove_zeros(
    df,
    col,
    ):
    return (
        df
        .log.query(
            expr=f"`{col}` == {df.set_index(col).sum(axis=1).loc[lambda x: x>0].index.tolist()}",
        )
    )
    
def get_diff_ins(
    df_, ## 
    df0_vars, ## all data
    col_value, # exp
    col_sid,
    col_group,
    
    col_diffid=None, # if = col_id ('gene id') : do not sum
    
    exclude_zeros=True,
):
    """
    Notes:
        df_ example: values are aggregated
        
            gene id	ids	ids var2	sample id	comparison	mRNA expression (TPM)
            0	ENSG00000001626	ENST00000649406;ENST00000649781;ENST00000699605	ENST00000003084;ENST00000426809;ENST0000067378...	ACH-000007	ref	0.0
            ..
            1	ENSG00000001626	ENST00000649406;ENST00000649781;ENST00000699605	ENST00000003084;ENST00000426809;ENST0000067378...	ACH-000236	test	0.0

    """
    ## query filter 
    df0_vars=(
        df0_vars
        ## filter
        .log.query(
            expr=(
                f"`{col_sid}` == {df_[col_sid].tolist()}"
            )
        )
    )
    
    if col_diffid is None:
        df0_vars=(
            df0_vars
            ## agg by gene
            .groupby(
                [
                    col_sid,
                    col_group,
                ]
            )
                [col_value].sum()
                .reset_index()
            .log(col_sid)
            .log(col_group)
        )
        col_diffid=col_group
    else:
        # 
        assert col_diffid in df0_vars, df0_vars.columns.tolist()
        df_=(
            df_
                .assign(
                    **{
                        col_diffid: lambda df: df['ids']
                      }
                )
        )
        
    df0_vars=(
        df0_vars
        ## filter
        .log.query(
            expr=(
                f"`{col_diffid}` != {df_[col_diffid].tolist()}"    # wont apply to gene sets anyways        
            )
        )
    )

    ## values matrix
    df0_mat=(
        pd.concat(
            [
                df_.loc[:,[col_diffid,col_sid,col_value,]],
                df0_vars,
            ],
            axis=0,
        )
        .log(col_diffid)
        .pivot(
            index=col_diffid,
            columns=col_sid,
            values=col_value,
        )
        .astype(float)
        .reset_index()
        .rd.assert_no_dups([col_diffid])
    )

    ## samples matrix    
    df0_sids=(
        df_
        .loc[:,[col_sid,'comparison']]
        .rd.assert_dense()
        .astype('str')
    )

    if exclude_zeros:
        df0_mat=_remove_zeros(
            df0_mat,
            col_diffid,
        )
    return df0_mat,df0_sids

def get_ro(
    env_name=None,
    src_r_home=None,
    verbose=False,
    pkg_method='micromamba',
    ):
    if env_name is not None:
        from roux.lib.sys import run_com
        com_='which R'
        for pre in [
            f"{pkg_method} run -n {env_name}",
            '']:
            com=f"{pre} {com_}"
            try:       
                src_r_home=run_com(
                    com,
                    verbose=verbose,
                ).strip()
            except Exception: 
                logging.warning(f'src_r_home not found: {com}')
        if src_r_home is None:
            raise ValueError(src_r_home)
        # if verbose:
        #     logging.info(src_r_home)
        src_r_home=src_r_home.replace(
            '/bin/',
            # f'/envs/{env_name}/lib/',
            '/lib/',
        )    
        if verbose:
            logging.info(src_r_home)  
        if 'env_name' not in src_r_home:
            from pathlib import Path
            src_r_home=f'{Path.home()}/{pkg_method}/envs/{env_name}/lib/R'
            logging.warning(f"inferred: {src_r_home}")

    if src_r_home is not None:
        import os
        # Set R_HOME to the path of the desired R installation
        os.environ["R_HOME"] = src_r_home
    else:
        if verbose:
            from rpy2.robjects.packages import importr
            base = importr('base')
            logging.info(base.R_home())        
            
    # Now import rpy2
    import rpy2.robjects as ro   
    if verbose:
        logging.info(ro.r('version'))
    return ro

def get_diff(
    df0_exp,
    df0_sids,

    groups=['test','ref'],
    col_sample='sample id', # e.g. 'sample id' 
    col_condition='comparison', # e.g. 'comparison'
    col_gene='gene id', # e.g. 'gene id'
    
    # bkg='limma',
    robust=True,
    trend=True,
    counts=False, # False: TPMs, else counts
    
    plot=False,    
    verbose=False,   
    **kws_get_ro,
    ):
    ro=get_ro(
        verbose=verbose,
        **kws_get_ro,
    )
    """

    Notes:
        Limma can not be multi-processed.

        if (!require("BiocManager", quietly = TRUE))
            install.packages("BiocManager")
        BiocManager::install("edgeR")        
        
    """
    
    ## Pre-processing
    ### Transformations
    df0_mat=(
        df0_exp.set_index(col_gene)
        .astype(int if counts else float)
    )
    
    df1_sids=(
        df0_sids
        .rename(
            columns={
            col_sample:'sample',
            col_condition:'condition',
            },
        )
        .loc[:,['sample','condition']]
        .assign(
            ## test vs ref
            condition=lambda df: df['condition'].replace({groups[0]:'group2',groups[1]:'group1'})
        )
        # importatnt: align the order of samples
        .set_index('sample')
            .loc[df0_mat.columns.tolist(),:]
            .reset_index()
    )

    from rpy2.robjects import pandas2ri
    pandas2ri.activate()
    ro.globalenv['df0_mat'] = pandas2ri.py2rpy(df0_mat)
    ro.globalenv['df1_sids'] = pandas2ri.py2rpy(df1_sids)
    
    # from string import Template
    
    # robust=str(robust).upper()
    # trend=str(trend).upper()
    # verbose=str(verbose).upper()
    
    ro.globalenv['counts'] = ro.BoolVector([counts])
    
    ro.globalenv['robust'] = ro.BoolVector([robust])
    ro.globalenv['trend'] = ro.BoolVector([trend])
    
    ro.globalenv['verbose'] = ro.BoolVector([verbose])
    ro.globalenv['plot'] = ro.BoolVector([plot])
    
    com="""
if (!verbose) {
    invisible(capture.output({
      # your code here
    }, type = "message"))  # suppress stderr
}

# mLoad <- function(...) { sapply(sapply(match.call(), as.character)[-1], require, character.only = TRUE) }
# mLoad(
#     # tools, # pathlib
#     # glue, # fstring
#     # yaml, # io
#     # dplyr, reshape2, tibble, reticulate, # data
#     # ggplot2, ## plots
#     limma, 
# )
library(limma)

# print(df1_sids)
# print(levels(df1_sids$condition))
design <- model.matrix(~ 0 + df1_sids$condition)
colnames(design) <- unique(sort(df1_sids$condition))

if (verbose) {
    print("Design Matrix:")
    print(design)
}

# pre. values
# --- Step 1: Data Pre-processing based on input format ---
if (counts) {
    
    library(edgeR)
    
    # cat("Using counts-based limma-voom workflow (recommended).")
    
    # Create a DGEList object from the counts data
    # This is a key step for the limma-voom workflow
    dge <- edgeR::DGEList(counts = df0_mat)


    # 2. Filter out lowly expressed genes
    # This is the crucial step that fixes the error. It uses a sensible
    # default to keep genes with sufficient expression across samples.
    # The filterByExpr function will intelligently choose which genes to keep
    # based on your experimental design.
    keep <- filterByExpr(dge, design) # assuming 'design' is your design matrix
    dge <- dge[keep, , keep.lib.sizes=FALSE]

    # Perform TMM normalization to calculate normalization factors
    # This accounts for library size differences
    dge <- edgeR::calcNormFactors(dge)
    
    # Apply the voom transformation to convert counts to logCPM and compute precision weights.
    # This is the core step that makes count data suitable for limma's linear models.
    # Use the voom-transformed data and weights for the linear model fit
    df1_mat <- limma::voom(dge, design, plot = plot)

} else {
    # cat("Using a direct log-transformation for TPMs (not recommended).")
    # cat("This approach may produce unreliable results as it bypasses voom's variance modeling.")
    # Lines of code which are different from using counts.
    # We apply a manual log2 transformation, adding a small offset to avoid log(0).
    # This treats the data as continuous, similar to microarray data.
    # No voom() function is used here.
    df1_mat <- log2(df0_mat + 1)    
}


# fitting
fit <- lmFit(
    df1_mat,
    design
)

# Define contrast: comparing group2 vs group1
contrast <- makeContrasts(group2 - group1, levels = design)
fit2 <- contrasts.fit(fit, contrast)

if (verbose) {
    print(robust)
    print(trend)
}

fit2 <- eBayes(
    fit2,
    robust = robust,
    trend  = trend, ## lowers fc magnitude
    # proportion = 0.001, ## does not have effect on fc
)

# Extract the Results
results <- topTable(fit2, number = Inf, sort.by = "P")
"""
    ro.r(com)
    
    return (
        pandas2ri.rpy2py(ro.globalenv['results'])
        .rename_axis(df0_mat.index.name)
        .reset_index()
        )

def ttest(a,b):
    """
    Steps:
        1. Take p-log before calculating the p-values to adjust the distributions.
        2. Set the parameters for the test, so the function has only to parameters.
    """
    from scipy.stats import ttest_ind
    from roux.stat.transform import plog
    
    def pre_stats(
        a,
    ):
        return list(map(lambda x: plog(x,p=1,base=2),a))
    return ttest_ind(
        pre_stats(a),
        pre_stats(b),
        alternative='two-sided',
        random_state=0,
        permutations=None
    )

## minimal implemetation (TODO: Optional fallback)
from scipy.optimize import minimize_scalar
def get_diff_shrunk(
    counts: pd.DataFrame,
    # condition: pd.Series,
    cols_a,# test
    cols_b,# ref
    size_factors=True,
    tau_method="mle",
    errors="raise",
):
    """Empirical Bayes shrinkage of log2 fold changes (LFC).

    Shrinks raw LFC estimates toward zero using a gene-wise posterior mean.
    Genes with low counts or high variability (large SE) are shrunk more
    aggressively, reducing the influence of noise on the final LFC estimate.

    --------------------------------------------------------------------------
    Model
    --------------------------------------------------------------------------
    Prior:      LFC_true  ~ N(0, tau^2)
    Likelihood: LFC_obs   | LFC_true ~ N(LFC_true, se^2)
    Marginal:   LFC_obs   ~ N(0, tau^2 + se^2)

    Posterior mean (closed-form conjugate update):

        LFC_shrunk = [ tau^2 / (tau^2 + se^2) ] * LFC_obs
                     |________________________|
                      shrinkage_factor (0, 1)

    --------------------------------------------------------------------------
    tau (prior_scale)
    --------------------------------------------------------------------------
    tau is the standard deviation of the prior distribution on true LFCs.
    It controls the *global* aggressiveness of shrinkage across all genes:

        - Large tau  → prior is broad  → trust the data  → less shrinkage.
        - Small tau  → prior is narrow → trust the prior → more shrinkage.

    tau is shared across all genes; per-gene shrinkage degree is modulated
    by se (standard error), so low-count genes are always shrunk more than
    high-count genes for the same tau.

    How to choose a fixed tau (tau_method=<float>):
        - Estimate tau once on a reference/pilot dataset using tau_method="mle",
          then hard-code the returned prior_scale value for downstream runs.
        - Alternatively, use the median absolute raw LFC of your reference as
          a rough proxy (equivalent to tau_method="median").
        - Typical range for bulk RNA-seq: 0.5–2.0. Values outside this range
          should be validated against known positive controls.
        - For cross-dataset comparisons, fix tau to the same value across all
          datasets to ensure shrunk LFCs are on a comparable scale.

    --------------------------------------------------------------------------
    Args
    --------------------------------------------------------------------------
    counts:
        Raw count matrix (genes x samples). Non-negative integers.
    condition:
        Binary indicator (0/1). LFC is computed as condition 1 vs 0.
    size_factors:
        If True, apply median-of-ratios normalization (DESeq2-style) before
        computing LFC and SE. If False, shrinkage is applied directly on raw
        counts. Disabling removes cross-sample library-size correction but
        the shrinkage logic (low-count moderation) remains intact.
    tau_method:
        Controls how the prior scale tau is determined.
            "mle"   : Estimate tau by maximizing marginal likelihood
                      log p(LFC_obs | tau). Data-adaptive, default.
            "median": Set tau = median(|LFC_raw|). Fast heuristic, robust
                      to LFC outliers.
            <float> : Use a user-supplied constant. Enables cross-dataset
                      comparability. See docstring above for guidance on
                      choosing a value.
    errors:
        'raise' to raise on input issues, else logs warning.

    Returns:
        dict with keys:
            lfc_raw:      Raw log2 fold changes.
            lfc_shrunk:   Shrunk log2 fold changes.
            se_raw:       Standard errors of raw LFCs.
            prior_scale:  tau used for shrinkage (float).
            mean:         Per-gene log geometric means (used for QC plots).
    """

    # --- QC ---
    # assert (len(set(condition))==2), "condition must be binary"
    assert counts.shape[1] == len(cols_a+cols_b), "counts columns must match condition length"
    assert (counts.values >= 0).all(), "counts must be non-negative"
    assert tau_method in ("mle", "median") or isinstance(
        tau_method, (int, float)
    ), "tau_method must be 'mle', 'median', or a float"

    # --- size factors (median-of-ratios, DESeq2 style) ---
    with np.errstate(divide="ignore"):
        log_counts = np.log(counts.values.astype(float))
    log_counts[~np.isfinite(log_counts)] = np.nan
    geo_means = np.nanmean(log_counts, axis=1)  # per-gene log geometric mean

    if size_factors:
        valid = np.isfinite(geo_means)
        sf = np.exp(
            np.nanmedian(log_counts[valid] - geo_means[valid, None], axis=0)
        )  # per-sample
    else:
        sf = np.ones(counts.shape[1])  # g: identity, no normalization

    # --- normalized counts ---
    normed = counts.values.astype(float) / sf[None, :]

    # --- raw LFC and SE via Wald-style estimation ---
    pseudocount = 1.0  # g: required; log(0) breaks LFC and SE
    idx1 = counts.columns.isin(cols_a)
    idx0 = counts.columns.isin(cols_b)

    mean1 = (normed[:, idx1] + pseudocount).mean(axis=1)
    mean0 = (normed[:, idx0] + pseudocount).mean(axis=1)
    lfc_raw = np.log2(mean1) - np.log2(mean0)

    # g: SE via delta method: Var(log(X)) ≈ Var(X) / mean(X)^2
    var1 = np.var(normed[:, idx1], axis=1, ddof=1) + pseudocount
    var0 = np.var(normed[:, idx0], axis=1, ddof=1) + pseudocount
    n1, n0 = idx1.sum(), idx0.sum()
    se_raw = np.sqrt(
        (var1 / (n1 * mean1**2) + var0 / (n0 * mean0**2)) / np.log(2) ** 2
    )
    se_raw = np.clip(se_raw, 1e-8, None)  # numerical floor

    # --- estimate or set tau ---
    if tau_method == "mle":
        # g: maximize log p(LFC_obs | tau); marginal: LFC_obs ~ N(0, tau^2 + se^2)
        def neg_log_marginal(log_tau):
            tau2 = np.exp(log_tau * 2)
            total_var = tau2 + se_raw**2
            return 0.5 * np.sum(np.log(total_var) + lfc_raw**2 / total_var)

        res = minimize_scalar(neg_log_marginal, bounds=(-6, 6), method="bounded")
        prior_scale = np.exp(res.x)

    elif tau_method == "median":
        prior_scale = float(np.median(np.abs(lfc_raw)))

    else:  # g: user-supplied float
        prior_scale = float(tau_method)

    # --- posterior mean (shrunk LFC) ---
    # LFC_shrunk = (tau^2 / (tau^2 + se^2)) * LFC_obs
    tau2 = prior_scale**2
    shrinkage_factor = tau2 / (tau2 + se_raw**2)  # per-gene, in (0, 1)
    lfc_shrunk = shrinkage_factor * lfc_raw

    return {
        "lfc_raw": pd.Series(lfc_raw, index=counts.index),
        "lfc_shrunk": pd.Series(lfc_shrunk, index=counts.index),
        "se_raw": pd.Series(se_raw, index=counts.index),
        "prior_scale": prior_scale,
        "mean": geo_means,
    }
