# AUTOGENERATED! DO NOT EDIT! File to edit: ../../modules_nbs/omics_io_prep.ipynb.

# %% auto 0
__all__ = ['read_table_prep', 'to_dataset', 'read_mods_df', 'to_mods_dt']

# %% ../../modules_nbs/omics_io_prep.ipynb 2
# source: datasets/modules_nbs/omics_io_prep.ipynb

import logging
logging.basicConfig(level='INFO')

from pathlib import Path


from roux.lib.df import loca, _get_preview_log_str
from roux.lib.io import read_table

import anndata as ad
import mudata as md
md.set_options(pull_on_update=False)
# from muon import MuData
# import muon as mu
# with mu.set_options(display_style="html", display_html_expand=0b000):
#     display(dt1)

def read_table_prep(
    values_path,
    col_id,

    col_sid='sample id',
    col_group=None,
    
    mod_name=None, #exp_tpm/me_del
    value_name=None, # custom value name e.g. {mod_name} log10
    
    ## filter
    sids=None,
    ids=None,
    
    ## mdata to map
    var=None,
    obs=None,

    kws_read_table=dict(
                use_paths=True,
                fast=5,
        ),
    fmt='lin', # melt
    # dtype='float',
    verbose=False,
    ):
    """
    Unified reader.
    """
    if values_path.endswith('.h5ad') or values_path.endswith('.h5mu'):
        ## get the dataframe
        if values_path.endswith('.h5ad'):
            dt1=ad.read_h5ad(values_path, backed='r')
            logging.info(dt1)
            if mod_name is None:
                mod_name=list(dt1.layers.keys())[0]

            df0_vars=(
                dt1
                .to_df(layer=mod_name)
                # sids,ids -> ids,sids
                .T
                )
            
            uns=dt1.uns
            if var is None: #custom
                var=dt1.var.reset_index()
                
        elif values_path.endswith('.h5mu'):
            import mudata as md
            dt1=md.read(values_path, backed=True)
            logging.info(dt1)
            # k=dt1.mod_names[0]
            if mod_name is None:
                mod_name=dt1.mod_names[0]
            
            df0_vars=(
                dt1
                .mod[mod_name].to_df()
                # sids,ids -> ids,sids
                .T
                )
            uns=dt1.mod[mod_name].uns
            if var is None: #custom
                var=dt1.mod[mod_name].var.reset_index()
                
        value_name=uns.get('col',mod_name)
        del uns
        dt1.file.close()
    else:
        df0_vars=(
            read_table(
                values_path,
                **kws_read_table,
            )
        )
        df0_vars=df0_vars.drop(['index'],axis=1,errors='ignore')
    logging.info(f"cols={df0_vars.columns.tolist()}")
    if col_group in df0_vars:
        ## set aside until melt
        df_ids=df0_vars.loc[:,[col_id,col_group]]
        df0_vars=df0_vars.drop([col_group],axis=1,errors='ignore')

    _melted=col_sid in df0_vars and col_id in df0_vars
    
    ## infer value_name
    if value_name is None:
        value_name=mod_name
        del mod_name
    if value_name is None:
        if _melted:
            value_name=df0_vars.select_dtypes('float').columns.tolist()
            assert len(value_name)==1, value_name
            value_name=value_name[0]

    ## filtering (before melting for sparing memory)
    if not _melted:
        # if df0_vars.index.names != [col_id]:
        if col_id in df0_vars:
            df0_vars=df0_vars.set_index(col_id)
        df0_vars=loca(
            df0_vars,
            ids,
            sids,
        )
        
    ## out mat    
    if fmt=='mat':
        if not _melted:
            return df0_vars
        else:
            # sids=df0_vars.select_dtypes(dtype).columns.tolist()
            # print(col_id,col_sid,value_name)
            return (
                df0_vars
                    .pivot(
                        index=col_id,
                        columns=col_sid,
                        values=value_name,
                    )
            )
    ## filtering (before melting for sparing memory)
    if not _melted:
        df0_vars=loca(
            df0_vars,
            ids,
            sids,
        )
            
        df0_vars=(
            df0_vars
            .melt(
                ignore_index=False,
                value_name=value_name,
                var_name=col_sid,
            )
            .reset_index()
        )
        if 'df_ids' in locals():
            df0_vars=(
                df_ids
                .merge(
                    right=df0_vars,
                    how='inner',
                    on=col_id,
                    validate='1:m',
                )
                )
        
    _melted=col_sid in df0_vars and col_id in df0_vars
    assert _melted, df0_vars.columns.tolist()
    
    df0_vars=(
        df0_vars
            .astype(
                {
                    **{
                        col_id:str,
                        col_sid:str,
                    },
                    **({} if col_group not in df0_vars else {
                        col_group:str
                    }),
                },
            errors='ignore',
            )
    )
    
    if var is not None:
        df0_vars=(
            df0_vars
            .merge(
                right=var,
                on=col_id,
                how='inner',
                validate="m:1",
            )
        )
    if obs is not None:
        df0_vars=(
            df0_vars
            .merge(
                right=obs,
                on=col_sid,
                how='inner',
                validate="m:1",
            )
        )
    logging.info(f"{df0_vars.shape} {_get_preview_log_str(df0_vars.head(1))}")
    return df0_vars
    
# def read_table_omics_mtx(
#     # values_paths['pt'],
#     # sids=sids['pt'],
#     # col_id='transcript id',
#     # col_group='gene id',
# ):
#     read_table_omics(
#     )


def to_dataset(
    dfs_values,
    outp,
    ):
    """
    To dataset.

    dfs_values:
        mods: 
            mod1: x
            mod2: x
        obs
        var
    """
    kws_write={}
    if outp.endswith('h5ad'):
        for i,(mod_name,df_x) in enumerate(dfs_values['mods'].items()):
            df_x=(
                df_x
                .sort_index(
                    axis=0,
                )
                .sort_index(
                    axis=1,
                )
                )
            if i==0:
                dt1 = ad.AnnData(
                    X=df_x.values,  # Main data matrix (expression data)
                    obs=dfs_values['obs'].loc[df_x.index.tolist(),:],  # Metadata for samples
                    var=dfs_values['var'].loc[df_x.columns.tolist(),:],  # Metadata for isoforms
                )
                dt1.layers[mod_name]=dt1.X
            else:
                assert (df_x.columns==dt1.var.index).all()
                assert (df_x.index==dt1.obs.index).all()
                dt1.layers[mod_name]=df_x.values
        logging.info(dt1)

        kws_write=dict(compression="gzip")
            
        # return dt1        
    elif outp.endswith('h5mu'):
        import mudata as md
        md.set_options(pull_on_update=False)        
        dts={}
        for mod_name,df_x in dfs_values['mods'].items():
            df_x=(
                df_x
                .sort_index(
                    axis=0,
                )
                .sort_index(
                    axis=1,
                )
                )
            dts[mod_name] = ad.AnnData(
                X=df_x.values,  # Main data matrix (expression data)
                obs=dfs_values['obs'].loc[df_x.index.tolist(),:],  # Metadata for samples
                var=dfs_values['var'].loc[df_x.columns.tolist(),:],  # Metadata for isoforms
            )
        dt1 = md.MuData(
            dts,
            axis=1
        )
        logging.info(dt1)
        assert (dts[mod_name].var.index==dt1.var.index).all()
        assert (dts[mod_name].obs.index==dt1.obs.index).all()
        dt1.var=dts[mod_name].var
        dt1.obs=dts[mod_name].obs

    Path(outp).parent.mkdir(parents=True,exist_ok=True)
    dt1.write(
        outp,
        **kws_write,
        )
    return outp

def read_mods_df(
    mods_cfg,
    col_id,
    col_group,
    col_sid='sample id',
    ):
    dfs=[]
    for k in mods_cfg:
        dfs.append(
            read_table_prep(
                mods_cfg[k]['path'],
                col_id=col_id,
                col_group=col_group,
                mod_name=mods_cfg[k]['col'],
            )
            )
    from roux.lib.dfs import merge_dfs
    return (
        merge_dfs(
            dfs,
            how='outer',
            on=[col_id,col_group,col_sid],
            validate='1:1'
        )
        .fillna({k:mods_cfg[k]['fillna'] for k in mods_cfg})
    )

def to_mods_dt(
    mods_cfg,
    outp,
    col_id,
    col_group,
    col_sid='sample id',
    ):
    df_merged=read_mods_df(
        mods_cfg,
        col_id=col_id,
        col_group=col_group,
        col_sid=col_sid,        
        )
    # df_merged.head()
    df_ids=(df_merged.loc[:,[col_id,col_group]].drop_duplicates().sort_values([col_id,col_group]))
    # df_ids
    Path(outp).parent.mkdir(parents=True,exist_ok=True)
    layers={
        k:(
            df_merged
            .pivot(
                index=col_sid,
                columns=col_id,
                values=mods_cfg.get('col',k),
            )
            .loc[:,df_ids[col_id].tolist()]
            # .set_index(col_id)
            .sort_index(axis=0)
            ) for k in mods_cfg
    }
    # return layers
    df_obs=layers[list(layers.keys())[0]].T.describe().T
    if outp.endswith('.h5ad'):
        dt = ad.AnnData(
                # X=df1_freq.values,
                obs=df_obs,
                var=df_ids.set_index(col_id),
                layers=layers,
                uns=mods_cfg,
            )
        dt.write(outp, compression="gzip")
    elif outp.endswith('.h5mu'):
        # logging.warning("h5mu is being saved, where h5ad should be preferred.")
        ## TODO: MuData because both var and obs do not necessarily align/be shared across modalities

        dt=md.MuData(
            {
                k:ad.AnnData(
                    X=df.values,
                    obs=df_obs,
                    var=df_ids.set_index(col_id),
                    uns=mods_cfg[k],
                ) for k,df in layers.items()
            },
            axis=1
        )
        dt.write(outp, compression="gzip")
    logging.info(dt)
    dt.file.close()
    return outp
